import Joi from "joi";

const sixteenYearsAgo = new Date();
sixteenYearsAgo.setFullYear(sixteenYearsAgo.getFullYear() - 16);

export const createMemberSchema = Joi.object({
  first_name: Joi.string().required(),
  last_name: Joi.string().required(),
  dateofbirth: Joi.date().max(sixteenYearsAgo).required().messages({
    "date.max": '"dateofbirth" must be in the past and it should not be below 16 years old',
    "date.base": '"dateofbirth" must be a valid date',
  }),
  gender: Joi.string().optional().allow(""),
  linked_msisdn: Joi.string().length(12).required(),
  email_address: Joi.string()
    .email({
      minDomainSegments: 2,
      tlds: {
        allow: [
          "com",
          "net",
          "org",
          "info",
          "biz",
          "name",
          "pro",
          "edu",
          "gov",
          "mil",
          "int",
          "us",
          "uk",
          "ca",
          "de",
          "fr",
          "au",
          "cn",
          "jp",
          "in",
          "br",
          "ru",
          "za",
          "mx",
          "dz",
          "ao",
          "bj",
          "bw",
          "bf",
          "bi",
          "cv",
          "cm",
          "cf",
          "td",
          "km",
          "cg",
          "cd",
          "ci",
          "dj",
          "eg",
          "gq",
          "er",
          "sz",
          "et",
          "ga",
          "gm",
          "gh",
          "gn",
          "gw",
          "ke",
          "ls",
          "lr",
          "ly",
          "mg",
          "mw",
          "ml",
          "mr",
          "mu",
          "yt",
          "ma",
          "mz",
          "na",
          "ne",
          "ng",
          "rw",
          "re",
          "sh",
          "st",
          "sn",
          "sc",
          "sl",
          "so",
          "za",
          "ss",
          "sd",
          "tz",
          "tg",
          "tn",
          "ug",
          "eh",
          "zm",
          "zw",
        ],
      },
    })
    .optional()
    .allow(""),
  marital_status: Joi.string().optional().allow(""),
  id_doc_country: Joi.string().required(),
  id_doc_type: Joi.string().required(),
  id_doc_number: Joi.string().required(),
});
